object: orig/G8ME01/sys/main.dol
hash: bc62d5e4674d139fd50d6c05694b34f955e37039
symbols: config/G8ME01/dol_symbols.txt
splits: config/G8ME01/splits.txt

modules:
- object: orig/G8ME01/files/rel/aaa.rel
  hash: f5b44ff83064e9bf61c4122c3715a68161da8ad0
  symbols: config/G8ME01/rels/aaa/symbols.txt
  splits: config/G8ME01/rels/aaa/splits.txt
- object: orig/G8ME01/files/rel/aji.rel
  hash: ce37fe134c24261fe870a9ef4389040ca6ea5bc8
  symbols: config/G8ME01/rels/aji/symbols.txt
  splits: config/G8ME01/rels/aji/splits.txt
- object: orig/G8ME01/files/rel/bom.rel
  hash: dbf15e225a5421f331801a0c7a10f5d68316ef94
  symbols: config/G8ME01/rels/bom/symbols.txt
  splits: config/G8ME01/rels/bom/splits.txt
- object: orig/G8ME01/files/rel/dmo.rel
  hash: 4338a674a7073765d3b4a966d3efdd80e5a8fa27
  symbols: config/G8ME01/rels/dmo/symbols.txt
  splits: config/G8ME01/rels/dmo/splits.txt
- object: orig/G8ME01/files/rel/dou.rel
  hash: 2bb25ac6dce0fefe34a8233a960b8da7456ced11
  symbols: config/G8ME01/rels/dou/symbols.txt
  splits: config/G8ME01/rels/dou/splits.txt
- object: orig/G8ME01/files/rel/eki.rel
  hash: a7e46734754529f5bc405ea12a5b2481fa8636b0
  symbols: config/G8ME01/rels/eki/symbols.txt
  splits: config/G8ME01/rels/eki/splits.txt
- object: orig/G8ME01/files/rel/gon.rel
  hash: e17361b42bb4bc5a9d62c355975b773b98018368
  symbols: config/G8ME01/rels/gon/symbols.txt
  splits: config/G8ME01/rels/gon/splits.txt
- object: orig/G8ME01/files/rel/gor.rel
  hash: 23b6de1981b4790548b7767d823bcea7e10e9765
  symbols: config/G8ME01/rels/gor/symbols.txt
  splits: config/G8ME01/rels/gor/splits.txt
- object: orig/G8ME01/files/rel/gra.rel
  hash: a6c1de813d9e3a2b8d03a47b2b5417c3cd8cb427
  symbols: config/G8ME01/rels/gra/symbols.txt
  splits: config/G8ME01/rels/gra/splits.txt
- object: orig/G8ME01/files/rel/hei.rel
  hash: 8c4278b5d815e5aed9c1f36c7e18b6922e6126ee
  symbols: config/G8ME01/rels/hei/symbols.txt
  splits: config/G8ME01/rels/hei/splits.txt
- object: orig/G8ME01/files/rel/hom.rel
  hash: c32a360fc1badbf73905c4cdf8828531395f103d
  symbols: config/G8ME01/rels/hom/symbols.txt
  splits: config/G8ME01/rels/hom/splits.txt
- object: orig/G8ME01/files/rel/jin.rel
  hash: b6527aa781ec807a6e7f81893bd6863909986e77
  symbols: config/G8ME01/rels/jin/symbols.txt
  splits: config/G8ME01/rels/jin/splits.txt
